
services:
  - type: web
    name: telegram-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
      - key: ADMIN_USER_ID
        sync: false
      - key: MANAGER_USER_IDS
        sync: false
      - key: RENDER_EXTERNAL_URL
        sync: false
